CREATE DATABASE SPT_ESPORTES;

USE SPT_ESPORTES;

CREATE TABLE SPT_PESSOAS(ID INT(10) PRIMARY KEY AUTO_INCREMENT,
						 CPF VARCHAR(14) NOT NULL UNIQUE KEY,
                         NOME VARCHAR(100) NOT NULL,
                         EMAIL VARCHAR(100) NOT NULL);
                         
/* TABELA ASSOCIATIVA ENTRE PESSOAS E TURMAS */ 
CREATE TABLE SPT_PESS_X_TURMAS(ID INT(10) PRIMARY KEY AUTO_INCREMENT,
							   PESS_ID INT(10) NOT NULL,
                               TURM_ID INT (10) NOT NULL);     

CREATE TABLE SPT_TURMAS(ID INT (10) PRIMARY KEY AUTO_INCREMENT,
						VAGAS INT(2) NOT NULL,
                        DIAS_AULAS VARCHAR(30) NOT NULL,
                        HORARIO TIME NOT NULL,
                        ID_LOCAL INT(10) NOT NULL,
                        ID_MODAL INT(10) NOT NULL);
                        
CREATE TABLE SPT_MODALIDADES (ID INT (10) PRIMARY KEY AUTO_INCREMENT,
							  DESCRICAO VARCHAR(300) NOT NULL,
							  TURNO VARCHAR(25) NOT NULL,
                              DURACAO VARCHAR(5) NOT NULL);
                              
CREATE TABLE SPT_LOCAIS ( ID INT(10) PRIMARY KEY AUTO_INCREMENT,
						  ENDERECO VARCHAR(100) NOT NULL,
                          NOME_LOCAL VARCHAR(100) NOT NULL);
                        
ALTER TABLE SPT_PESS_X_TURMAS
ADD FOREIGN KEY (PESS_ID) REFERENCES SPT_PESSOAS(ID); 
ALTER TABLE SPT_PESS_X_TURMAS
ADD FOREIGN KEY (TURM_ID) REFERENCES SPT_TURMAS(ID);    
   
ALTER TABLE SPT_TURMAS
ADD FOREIGN KEY (ID_LOCAL) REFERENCES SPT_LOCAIS(ID); 

ALTER TABLE SPT_TURMAS
ADD FOREIGN KEY (ID_MODAL) REFERENCES SPT_MODALIDADES(ID);  

ALTER TABLE SPT_PESSOAS ADD TIPO_USUARIO INT(2);
ALTER TABLE SPT_PESSOAS ADD SENHA VARCHAR(20);

/* regra teve que ser dropada por erro aleatorio do java {PROBLEMA RESOLVIDO} */
/* ALTER TABLE SPT_TURMAS
DROP FOREIGN KEY spt_turmas_ibfk_2; */


SELECT * FROM SPT_PESSOAS WHERE CPF = '123.123.123-99' AND SENHA = '1234';


SELECT * FROM SPT_PESSOAS;

COMMIT;
SELECT LOCA.ENDERECO ENDERECO FROM SPT_LOCAIS LOCA;

SELECT * FROM SPT_LOCAIS;
SELECT * FROM SPT_MODALIDADES;

INSERT INTO SPT_PESSOAS(CPF, NOME, EMAIL, TIPO_USUARIO, SENHA) VALUES('1111','Gustavo','gustavo@teste.com','1','1234');
INSERT INTO SPT_LOCAIS (ID, ENDERECO, NOME_LOCAL) VALUES ('1', 'teste 01', 'endereco001');

DELETE FROM SPT_TURMAS WHERE ID_MODAL = 0;

SELECT * FROM SPT_TURMAS;